repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # ✅ Verified valid tag
    hooks:
      - id: isort

 
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2  # check for latest: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
      - id: ruff-format  # optional if you want black-style formatting
