repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  # Use a local pytest hook so we don't rely on a remote repo manifest.
  - repo: local
    hooks:
      - id: pytest
        name: pytest (with coverage)
        entry: pytest
        language: system   # use your current venv
        pass_filenames: false
        args:
          - --cov=src
          - --cov-branch
          - --cov-report=term
          - --cov-report=html
          - --cov-fail-under=85
