
services:
  climate-compare:
    build: .
    container_name: climate-compare
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
