name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

 name: Deploy to EC2
 if: success()
 uses: appleboy/ssh-action@v1.0.3
 with:
   host: ${{ secrets.EC2_HOST }}
   username: deploy
   key: ${{ secrets.EC2_SSH_KEY }}
   strict_host_key_checking: true
   known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}
   script: |
     cd /var/www/html
     git remote set-url origin git@github.com:frankbhome/climate-compare.git
     git pull origin main
